apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: links.projectriff.io
spec:
  scope: Namespaced
  group: projectriff.io
  version: v1alpha1
  names:
    kind: Link
    plural: links
    singular: link
