apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: topics.projectriff.io
spec:
  scope: Cluster
  group: projectriff.io
  version: v1alpha1
  names:
    kind: Topic
    plural: topics
    singular: topic
