jobs:

- job: unit
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      mac:
        imageName: 'macos-10.13'
      windows:
        imageName: 'windows-2019'
  pool:
    vmImage: $(imageName)
  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/opt/hostedtoolcache/go/1.12.0/x64' # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(build.repository.name)' # Path to the module's code
  steps:
  - template: ci/unit-test-steps.yml
  displayName: 'Unit test'

- job: stage
  dependsOn: unit
  pool:
    vmImage: ubuntu-16.04
  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/opt/hostedtoolcache/go/1.12.0/x64' # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(build.repository.name)' # Path to the module's code
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  steps:
  - template: ci/install-go-steps.yml
  - template: ci/install-gcloud.yml
  - bash: ./ci/stage.sh
    env:
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
    workingDirectory: '$(modulePath)'
    displayName: 'Stage riff release artifacts'
  displayName: 'Stage'

# TODO restore FATS tests
- job: fats
  dependsOn: stage
  pool:
    vmImage: ubuntu-16.04
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  steps:
  - bash: echo 'TODO implement me'
  displayName: 'FATS'

- job: publish
  dependsOn: fats
  pool:
    vmImage: ubuntu-16.04
  condition: |
    and(
      succeeded(),
      ne(variables['Build.Reason'], 'PullRequest'),
      or(
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        and(
          startsWith(variables['Build.SourceBranch'], 'refs/heads/v'),
          endsWith(variables['Build.SourceBranch'], 'x')
        )
      )
    )
  steps:
  - template: ci/install-gcloud.yml
  - bash: ./ci/publish.sh $(Build.SourceBranchName)
    env:
      GCLOUD_CLIENT_SECRET: '$(GcloudClientSecret)'
    displayName: 'Publish riff release artifacts'
  displayName: 'Publish'
