apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: topics.extensions.sk8s.io
versions:
- name: v1
spec:
  scope: Namespaced
  group: extensions.sk8s.io
  version: v1
  names:
    kind: Topic
    plural: topics
    singular: topic
