# Default values for riff.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
create:
  crd: true
  faas: true
  rbac: false
rbac:
  apiVersion: v1beta1
functionController:
  replicaCount: 1
  image:
    repository: projectriff/function-controller
    tag: 0.0.3
    pullPolicy: IfNotPresent
  sidecar:
    image:
      tag: 0.0.3
topicController:
  replicaCount: 1
  image:
    repository: projectriff/topic-controller
    tag: 0.0.3
    pullPolicy: IfNotPresent
httpGateway:
  replicaCount: 1
  image:
    repository: projectriff/http-gateway
    tag: 0.0.3
    pullPolicy: IfNotPresent
  service:
    name: http
    type: LoadBalancer
    externalPort: 80
zookeeper:
  replicaCount: 1
  image:
    repository: wurstmeister/zookeeper
    tag: 3.4.6
    pullPolicy: IfNotPresent
  service:
    name: zookeeper
    type: ClusterIP
    externalPort: 2181
    internalPort: 2181
kafka:
  replicaCount: 1
  image:
    repository: wurstmeister/kafka
    tag: 0.11.0.1
    pullPolicy: IfNotPresent
  service:
    name: kafka
    type: ClusterIP
    externalPort: 9092
    internalPort: 9092
