kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: projectriff-riff
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["projectriff.io"]
    resources: ["functions", "topics", "links"]
    verbs: ["get", "list", "watch"]
