apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: function-controller
spec:
  replicas: 1
  template:
    metadata:
      name: function-controller
      labels:
        app: riff
        component: function-controller
    spec:
      containers:
      - image: projectriff/function-controller:0.0.3-snapshot
        name: function-controller
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: kafka:9092
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: zookeeper:2181
        - name: RIFF_FUNCTION_SIDECAR_TAG
          value: 0.0.3-snapshot
      serviceAccountName: riff-sa
