apiVersion: v1
kind: Service
metadata:
  name: topic-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080
    nodePort: 30111
  - port: 443
    name: https
    targetPort: 8443
  selector:
    app: topic-gateway
