apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topic-controller
spec:
  replicas: 1
  template:
    metadata:
      name: topic-controller
      labels:
        app: sk8s
        component: topic-controller
    spec:
      containers:
      - image: sk8s/topic-controller:0.0.1-SNAPSHOT
        name: topic-controller
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: JAVA_TOOL_OPTIONS
          value: '-Xmx512m'
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: kafka:9092
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: zookeeper:2181
