apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projectriff-riff-http-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: http-gateway
      labels:
        app: riff
        component: http-gateway
    spec:
      containers:
      - image: projectriff/http-gateway:0.0.7
        name: http-gateway
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /application/status
            port: 8080
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /application/status
            port: 8080
          periodSeconds: 5
        env:
        - name: KAFKA_BROKERS
          value: projectriff-kafka.riff-system:9092
        - name: RIFF_HTTP_HEADERS_WHITELIST
          value: # Add,A-Comma-Separated,List-Of,Headers,To-Whitelist,Here
      serviceAccountName: projectriff-riff
