apiVersion: v1
kind: Service
metadata:
  name: projectriff-riff-http-gateway
  labels:
    app: riff
    component: http-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080
  - port: 443
    name: https
    targetPort: 8443
  selector:
    component: http-gateway
