apiVersion: v1
kind: Service
metadata:
  name: projectriff-riff-function-controller-debug
  labels:
    app: riff
    component: function-controller
spec:
  type: NodePort
  ports:
  - name: delve
    port: 2345
    nodePort: 30102
    targetPort: 2345
  selector:
    component: function-controller
