apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projectriff-riff-function-controller
spec:
  replicas: 1
  template:
    metadata:
      name: function-controller
      labels:
        app: riff
        component: function-controller
    spec:
      containers:
      - image: projectriff/function-controller:0.0.8-snapshot
        name: function-controller
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: KAFKA_BROKERS
          value: projectriff-kafka.riff-system:9092
        - name: RIFF_FUNCTION_SIDECAR_REPOSITORY
          value: projectriff/function-sidecar
        - name: RIFF_FUNCTION_SIDECAR_TAG
          value: 0.0.8-snapshot
      serviceAccountName: projectriff-riff
